/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagesecurity;

/**
 *
 * @author Suman
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName = new javax.swing.JLabel();
        Enter_Name = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Enter_Password = new javax.swing.JPasswordField();
        SignIn = new javax.swing.JButton();
        SignUp = new javax.swing.JLabel();
        ForgotPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 500));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        UserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserName.setText("UserName: ");
        getContentPane().add(UserName);
        UserName.setBounds(90, 20, 160, 80);

        Enter_Name.setText("jTextField1");
        Enter_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_NameActionPerformed(evt);
            }
        });
        getContentPane().add(Enter_Name);
        Enter_Name.setBounds(280, 40, 170, 40);

        Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password.setText("Password: ");
        getContentPane().add(Password);
        Password.setBounds(90, 110, 140, 50);

        Enter_Password.setText("jPasswordField1");
        Enter_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Enter_Password);
        Enter_Password.setBounds(280, 110, 170, 40);

        SignIn.setBackground(new java.awt.Color(52, 164, 146));
        SignIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SignIn.setText("Sign In");
        getContentPane().add(SignIn);
        SignIn.setBounds(320, 180, 140, 40);

        SignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SignUp.setForeground(new java.awt.Color(0, 102, 204));
        SignUp.setText("Forgot Password: ");
        getContentPane().add(SignUp);
        SignUp.setBounds(90, 180, 117, 22);

        ForgotPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ForgotPassword.setForeground(new java.awt.Color(0, 102, 204));
        ForgotPassword.setText("Dont have an account? SignUp");
        getContentPane().add(ForgotPassword);
        ForgotPassword.setBounds(90, 210, 192, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Enter_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Enter_PasswordActionPerformed

    private void Enter_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Enter_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Enter_Name;
    private javax.swing.JPasswordField Enter_Password;
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JLabel Password;
    private javax.swing.JButton SignIn;
    private javax.swing.JLabel SignUp;
    private javax.swing.JLabel UserName;
    // End of variables declaration//GEN-END:variables
}
