/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagesecurity.ImageTotext;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.*;

/**
 *
 * @author Suman
 */
public class DashBoard_Layout extends javax.swing.JPanel {
    private javax.swing.JButton RestoreImage;
    private javax.swing.JButton ImageToText;
    private javax.swing.JButton TextToImage;
    private JMenu menu1;
    /**
     * Creates new form DashBoard
     */
    public DashBoard_Layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void run(javax.swing.JPanel DashBoard,Container container){
        
        DashBoard.setBackground(new java.awt.Color(191, 181, 173));
        DashBoard.setLayout(null);
        RestoreImage = new javax.swing.JButton();
        ImageToText = new javax.swing.JButton();
        TextToImage = new javax.swing.JButton();
        RestoreImage.setBackground(new java.awt.Color(150, 145, 183));
        RestoreImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RestoreImage.setText("Unable to Restore Image");
        RestoreImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardLayout card = (CardLayout) container.getLayout();
                card.show(container, "card5");
            }
        });
        DashBoard.add(RestoreImage);
        RestoreImage.setBounds(310, 220, 280, 60);

        ImageToText.setBackground(new java.awt.Color(150, 145, 183));
        ImageToText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ImageToText.setText("Image Converter");
        ImageToText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardLayout card = (CardLayout) container.getLayout();
                card.show(container, "card3");
            }
        });
        DashBoard.add(ImageToText);
        ImageToText.setBounds(130, 100, 280, 60);

        TextToImage.setBackground(new java.awt.Color(150, 145, 183));
        TextToImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextToImage.setText("Text Converter");
        TextToImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        DashBoard.add(TextToImage);
        TextToImage.setBounds(490, 100, 280, 60);
    
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
